# Special Continuous Distributions

## Continuous Uniform Random Variables

$$
X \sim Unif(a,b)
$$

$$
\begin{equation}
f(x) = \begin{cases}
\frac{1}{b-a} & \text{if } a \le x \le b\\
0 &  \text{otherwise}
\end{cases}
\end{equation}
$$

> $X$ is uniformly distributed over the interval $[a,b]$, so at all points we have the same height for the PDF. Any two intervals of the same length can occur with equal probability.

**Center and Dispersion**

$$
E(X) = \frac{a+b}{2} \qquad Var(X) = \frac{(b-a)^2}{12} \qquad  \sigma_x = \frac{b-a}{\sqrt{12}}
$$

**Additional Notes**

-   There is also a discrete uniform random variable which is similarly defined.

-   A piece-wise constant pdf has a total area of 1, but can have discontinuities

## Exponential Random Variables

$$
X \sim Exponential(\lambda) \\ \text{or} \\ X \sim Exponential(\theta = \frac{1}{\lambda})
$$

$$
\begin{equation}
f_X(x) = F'(x) = \begin{cases}
\lambda e^{-\lambda x} & \text{if } x \ge 0 \\
0 &  x < 0
\end{cases}
\end{equation}
$$

**Center and Dispersion**

$$
E(X) = \sigma_x = \frac{1}{\lambda} \qquad Var(X) = \frac{1}{\lambda^2} 
$$

**Additional Notes**

-   Memoryless property
-   Relationship between Exponential and Geometric

$$
\begin{equation}
f_X(x) = F'(x) = \begin{cases}
\lambda e^{-\lambda x} & \text{if } x \ge 0 \\
0 &  x < 0
\end{cases}
\end{equation}
$$

## Gaussian Random Variables

### Standard Normal Random Variable

> A special case of the normal distribution that is used to calculated probabilities for any normal distribution, without having to calculate using it's PDF.
>
> $$
> Z\sim N(0,1)
> $$

$$
f(z) = \frac{1}{\sqrt{2\pi}}\exp [-\frac{z^2}{2}]
$$

$$
F(z) = \frac{1}{\sqrt{2\pi}}\int_{-\infty}^z\exp [\frac{-t^2}{2}]dt
$$

**Center and Dispersion**

$$
E(X) = 0 \qquad Var(X) = 1
$$

**Additional Notes**

### Normal Random Variable

$$
f(x) = \frac{1}{\sigma \sqrt{2\pi}} \exp [-\frac{(x-\mu)^2}{2\sigma^2}] \qquad -\infty < x<\infty
$$

**Center and Dispersion**

$$
E(X) = \sigma_x = \frac{1}{\lambda} \qquad Var(X) = \frac{1}{\lambda^2} 
$$

**Additional Notes**
