# Axioms of Kolmogorov

There are three rules defined for creating a probabilistic model:

(1) The probability of an event must be greater than zero

(2) That the probabilities for all disjoint events in a sample space must sum to one

(3) The total probability for the union of events is equal to the sum of their individual probabilities.

This is an ultra simplified statement of the axioms that govern modern probability theory. In 1933, these rules were formally axiomized by the great Andrey Nikolaevich Kolmogorov.

Before describing the axioms more formally, lets review some set theory.

## Sets, Sample Spaces, and events

-   Sets are collections of distinct elements.
-   A sample space is the set of disjoint, collectively exhaustive outcomes taken at a determined level of granularity.
-   A sample space can be described as finite or infinite, discrete or continuous.

### Definitions and LaTex code.

```{r, echo=FALSE}
library(knitr)
library(kableExtra)

table_data <- data.frame(
  Symbol = c("$\\sim$","$=$","$\\cup$", "$\\cap$", "$\\in$", "$\\varnothing$", 
             "$\\Omega$, $S$", "$\\omega$, $s$", "$\\subset$", "$\\subseteq$", 
             "$\\bigcup$", "$\\bigcap$"),
  
  Name = c("Similar", 
           "Equality, 
           sets are identical i.e. contain the same elements",
           "Intersection",
           "Union", 
           "Belongs to", 
           "Null set", 
           "Universal set", 
           "Atom, singleton", 
           "Proper subset, S is contained within A, sometimes used  S = A",
           "Subset, if S is contained within A",
           "infinitary union, generalized union, unified union",
           "infinitary intersection, generalized intersection, unified intersection cap"),
  
  LaTeX = c("\\\\sim", "=","\\\\cup", "\\\\cap", "\\\\in", "\\\\varnothing",
            "\\\\Omega", "\\\\omega", "\\\\subset", "\\\\subseteq", "\\\\bigcup", "\\\\bigcap")
  
  )

kable_styling(kable(table_data, format = "html", escape = FALSE))
```

### More Set Definitions

complement, sum, difference, certainty, impossibility, mutual exclusivity..

### Relational Laws

Communicative

Associative

Distributive

DeMorgan's 1st and 2nd laws

[add proofs, also identities are usually proven elementwise]

## Axioms of Kolmogorov

(1) **Non-negativity Axiom**

$$
\text{For any event A in our sample space, } \mathbb{P}(A)≥0
$$

(2) **Unity Axiom**

$$
\text{Normalization, also called the assumption of unit measure,}\\ \text{defines the probability of the sample space }
\Omega \text{ as } \mathbb{P}(\Omega)=1
$$

(3) **$\sigma$-additivity Axiom**

~~Any countable pairwise disjoint sequence (i.e. A1,A2,\...), even countably infinite sequences of events satisfies~~

> $P(\bigcup_{i=1}^{\infty}A_{i}) = \sum_{n=1}^{\infty}P(A_{i})$ where pairwise disjoint: i.e. $A_iA_j = \varnothing$, where $i \neq j$ (countable sequence of events: $A_1,A_2,...$)


Finite additivity is 

## Implied consequences of the Axioms

Demonstrating these immediate consequences illustrates the power of the third axiom, and its interaction with the remaining two axioms.

> (Theorem 1.1) Probability of the empty set
>
> $P(\varnothing) = 0$

(Theorem 1.2) Finite Additivity

(Theorem 1.3) "Average"

(Theorem 1.4) The complement rule

(Theorem 1.5) Monotonicity

-   Corollary: The numeric bound

(Theorem 1.6) Inclusion-Exclusion Principal

(Theorem 1.7) P(A) = P(AB) + P(AB\^C)

(Theorem 1.8) Continuity of Probability Function

Booles ineqauilty

### A word of Probability Measures

## CONTINUITY OF PROBABILITY FUNCTIONS
