# Combinatorics

## Counting Principal

Fundamental Counting Principle a.k.a. generalized counting principal,

Also known as the rule of product, or the multiplication principal.

> Let $E_1, E_2, ..., E_k$ be sets with $n_1,n_2, ...,n_k$ elements,respectively. Then there are $n_1×n_2×n_3×···×n_k$ ways in which we can, first, choose an element of $E_1$, then an element of $E_2$, then an element of $E_3$... and finally an element of $E_k$.

[Combinatorial principles - Wikipedia](https://en.wikipedia.org/wiki/Combinatorial_principles)

## Number of Sets in a Subset

The set of all subsets of A is called the **power set** of A.

We can calculate the number of subsets in a set as $2^n$, because each element can be either included or excluded (hence the two options)

Mathematically we can say that

## Permutations

A permutation is the number of ways we can order $n$ distinct objects, from the general counting principal it follows that we have $n$ ways to make the first selection, the we will have one less ways to make our next selection, and so on. For example if we have ten objects, there is ten ways to...

$$
(n)(n−1)(n−2)···(1)=n!
$$

This is because of there are of the ways to $n$ ways to choose the first object, n-1 ways to choose the second, all the way to only $1$ possible way to choose the last object.

We use the notation $_nP_r$ to denote the number of permutations of a set $A$ containing $n$ elements taken $r$ at a time where $(1 ≤ r ≤ n)$

The number of r-element permutations of a set containing n objects is given by

$$
_nP_r = \frac{n!}{(n-r)!}
$$

(note: to avoid division by zero when $n=r$ we define $0! = 1$)

To derive the formula for $_nP_r$ we consider the number of choices for each selection.

Since $A$ has $n$ elements, the number of choices for the first object in the $r$-element permutation is $n$. For the next selection there will be $n-1$ options, followed by $n-2$ options for the selection that follows after that, we do this until our last selection, **which is the** $r$**th object.** This object has possible $n − (r − 1)$ choices.

This leads us to the equation

$$
_nP_r =n(n−1)(n−2)···(n−r+1)
$$

We can also note how this relates to a simple permutation which we discussed above

$$
_nP_n =n(n−1)(n−2)···(n−n+1)=n!
$$

How we get our general formula $_nP_r$ is by manipulating the equation $n(n−1)(n−2)···(n−r+1)$ which is done by multiplying both sides by $(n-r)!$, then dividing both sides by $(n-r)!$ Which leads us to the formula

$$
_nP_r = \frac{n!}{(n-r)!}
$$

[reorganize to follow and add actual derivation]

However the formula above is valid only if all of the objects of the set are distinguishable from each other. If there are repeated elements (e.g. the letter E in the word "BERKELEY") we must take

add [karapanian veusus brungard]

$$
\frac{n!}{n_1! × n_2 ! × · · · × n_k!}
$$

An example of repeated elements in a permutation problem would be: *How many different 10-letter codes can be made using three a's, four b's, and three c's?*

Which would have the solution $\frac{10!}{(3!*4!*3!)}$, since you need to use to above theorem to divide out the elements that would otherwise be over-counted.

## Combinations

[motivation add how its different than combination]

we have for $r \le n$

$$
\binom{n}{r}=\frac{n!}{r!(n-r)!}
$$

We are calculating the number of $r$-element subsets from a $n$-element set, where order matters. This is the number of all r-element combinations of n objects, where we only use valid non-negative integers (e.g. 0,1,2, ...) where $r \le n$.

[add derivation!!!!! xr! = npr]

consider

$$
\binom{n}{n}=\binom{n}{0}=1
$$

$$
\binom{n}{n}=\frac{n!}{n!(n-n)!=1}
$$

consider

$$
\binom{n}{1}=\binom{n}{n-1}
$$

consider

where $0 \le r \le n$

$$
\binom{n}{r}=\binom{n}{n-r}
$$

and

$$
\binom{n+1}{r}=\binom{n}{r}+\binom{n}{r-1}
$$

[write more thoughts about this and how to verify algebraically or using combinatorics]


[add unordered sampling with replacement]

[example 2.22 and binomial expansion]
