# Dists 

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(fig.height = 4)
```

```{r}
library(shiny)


# Define UI for the app
ui <- fluidPage(

  sidebarLayout(
    sidebarPanel(
      sliderInput("n", "n:", min = 1, max = 50, value = 10),
      sliderInput("p", "p:", min = 0, max = 1, value = 0.5, step = 0.1),
      verbatimTextOutput("text")
    ),
    mainPanel(
      plotOutput("plot"),
      textOutput("my_text")
    )
  )
)

# Define server logic for the app
server <- function(input, output) {
  # Generate binomial distribution with parameters n and p
  output$plot <- renderPlot({
    x <- 0:input$n
    y <- dbinom(x, size = input$n, prob = input$p)
    barplot(y, names.arg = x, xlab = "X", ylab = "Probability", main = "Binomial Distribution", col = "#49876a", border = "black")
  })
  
  # Calculate mean and variance of the binomial distribution
  output$text <- renderPrint({
    mean <- input$n * input$p
    var <- input$n * input$p * (1 - input$p)
    cat("Mean: ", mean, "\n")
    cat("Variance: ", var, "\n")
  })

  
}
  


# Run the app
shinyApp(ui = ui, server = server)
```

```{r}

# Define UI for the app
ui <- fluidPage(

  sidebarLayout(
    sidebarPanel(
      sliderInput("n", "n:", min = 1, max = 50, value = 10),
      sliderInput("p", "p:", min = 0, max = 1, value = 0.5, step = 0.1),
      verbatimTextOutput("text")
    ),
    mainPanel(
      plotOutput("plot"),
      textOutput("my_text")
    )
  )
)

# Define server logic for the app
server <- function(input, output) {
  # Generate geometric distribution with parameters n and p
  output$plot <- renderPlot({
    x <- 0:input$n
    y <- dgeom(x, prob = input$p)
    barplot(y, names.arg = x, xlab = "X", ylab = "Probability", main = "Geometric Distribution", col = "#49876a", border = "black")
  })
  
  # Calculate mean and variance of the geometric distribution
  output$text <- renderPrint({
    mean <- 1 / input$p
    var <- (1 - input$p) / input$p^2
    cat("Mean: ", mean, "\n")
    cat("Variance: ", var, "\n")
  })
}

# Run the app
shinyApp(ui = ui, server = server)

```

```{r}

# Define UI for the app
ui <- fluidPage(
  
  sidebarLayout(
    sidebarPanel(
      sliderInput("r", "r:", min = 1, max = 50, value = 10),
      sliderInput("p", "p:", min = 0, max = 1, value = 0.5, step = 0.1),
      verbatimTextOutput("text")
    ),
    mainPanel(
      plotOutput("plot"),
      textOutput("my_text")
    )
  )
)

# Define server logic for the app
server <- function(input, output) {
  # Generate negative binomial distribution with parameters r and p
  output$plot <- renderPlot({
    x <- 0:input$r
    y <- dnbinom(x, size = input$r, prob = input$p)
    barplot(y, names.arg = x, xlab = "X", ylab = "Probability", main = "Negative Binomial Distribution", col = "#49876a", border = "black")
  })
  
  # Calculate mean and variance of the negative binomial distribution
  output$text <- renderPrint({
    mean <- input$r * (1 - input$p) / input$p
    var <- input$r * (1 - input$p) / input$p^2
    cat("Mean: ", mean, "\n")
    cat("Variance: ", var, "\n")
  })
  
}

# Run the app
shinyApp(ui = ui, server = server)
```

```{r}

# Define UI for the app
ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(
      sliderInput("lambda", "λ:", min = 0, max = 50, value = 10, step = 0.1),
      verbatimTextOutput("text")
    ),
    mainPanel(
      plotOutput("plot"),
      textOutput("my_text")
    )
  )
)

# Define server logic for the app
server <- function(input, output) {
  # Generate Poisson distribution with parameter lambda
  output$plot <- renderPlot({
    x <- 0:50
    y <- dpois(x, lambda = input$lambda)
    barplot(y, names.arg = x, xlab = "X", ylab = "Probability", main = "Poisson Distribution", col = "#49876a", border = "black")
  })
  
  # Calculate mean and variance of the Poisson distribution
  output$text <- renderPrint({
    mean <- input$lambda
    var <- input$lambda
    cat("Mean: ", mean, "\n")
    cat("Variance: ", var, "\n")
  })
}

# Run the app
shinyApp(ui = ui, server = server)

```

```{r}

# Define UI for the app
ui <- fluidPage(

  
  sidebarLayout(
    sidebarPanel(
      sliderInput("n", "Sample size (n):", min = 1, max = 50, value = 10),
      sliderInput("k", "Number of successes in population (K):", min = 1, max = 50, value = 5),
      sliderInput("N", "Population size (N):", min = 1, max = 100, value = 20),
      verbatimTextOutput("text")
    ),
    
    mainPanel(
      plotOutput("plot")
    )
  )
)

# Define server logic for the app
server <- function(input, output) {
  
  # Generate hypergeometric distribution with parameters n, k, and N
  output$plot <- renderPlot({
    x <- 0:input$n
    y <- dhyper(x, m = input$k, n = input$N - input$k, k = input$n)
    barplot(y, names.arg = x, xlab = "X", ylab = "Probability", main = "Hypergeometric Distribution", col = "#49876a", border = "black")
  })
  
  # Calculate mean and variance of the hypergeometric distribution
  output$text <- renderPrint({
    mean <- input$n * input$k / input$N
    var <- input$n * input$k / input$N * (1 - input$k / input$N) * ((input$N - input$n) / (input$N - 1))
    cat("Mean: ", mean, "\n")
    cat("Variance: ", var, "\n")
  })
}

# Run the app
shinyApp(ui = ui, server = server)

```
